title: Rails Generate
name: Rails Generate
url: http://example.org
description: A Coding Blog

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
