title: The Wall
name: The Wall
url: http://calderete.github.io/
description: 
baseurl: http://calderete.github.io/

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
