title: Silo 1
name: Silo 1
url: http://calderete.github.io/
description: Silo 1
baseurl: /

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments
plugins: ['jekyll-paginate']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
